-- Sample data for LuxZoraCraft
-- Insert sample categories and products

-- Insert admin user
INSERT INTO users (email, name, is_admin, email_verified) VALUES 
('nealmanawat@gmail.com', 'Neal Manawat', true, true)
ON CONFLICT (email) DO UPDATE SET 
  is_admin = true,
  name = EXCLUDED.name,
  email_verified = true;

-- Insert categories
INSERT INTO categories (name, slug, description, image_url, is_active) VALUES 
('Necklaces', 'necklaces', 'Elegant necklaces for every occasion', '/images/categories/necklaces.jpg', true),
('Earrings', 'earrings', 'Beautiful earrings to complete your look', '/images/categories/earrings.jpg', true),
('Rings', 'rings', 'Stunning rings for special moments', '/images/categories/rings.jpg', true),
('Bracelets', 'bracelets', 'Delicate bracelets for everyday wear', '/images/categories/bracelets.jpg', true),
('Pendants', 'pendants', 'Unique pendants with precious stones', '/images/categories/pendants.jpg', true),
('Bangles', 'bangles', 'Traditional and modern bangles', '/images/categories/bangles.jpg', true);

-- Get category IDs for products
-- Insert sample products
INSERT INTO products (
  name, slug, description, short_description, price, compare_price, sku, 
  quantity, category_id, images, tags, is_featured, is_active,
  material, color, gemstone, metal_purity, warranty_period
) VALUES 
(
  'Diamond Solitaire Necklace',
  'diamond-solitaire-necklace',
  'A stunning diamond solitaire necklace crafted in 18k white gold. Features a brilliant round-cut diamond pendant that captures light beautifully from every angle.',
  'Elegant diamond solitaire necklace in 18k white gold',
  45000.00,
  50000.00,
  'DSN001',
  15,
  (SELECT id FROM categories WHERE slug = 'necklaces'),
  ARRAY['/images/products/diamond-necklace-1.jpg', '/images/products/diamond-necklace-2.jpg'],
  ARRAY['diamond', 'solitaire', 'white-gold', 'luxury'],
  true,
  true,
  '18k White Gold',
  'White',
  'Diamond',
  '18k',
  24
),
(
  'Pearl Drop Earrings',
  'pearl-drop-earrings',
  'Classic pearl drop earrings featuring lustrous freshwater pearls set in sterling silver. Perfect for both casual and formal occasions.',
  'Elegant freshwater pearl drop earrings in sterling silver',
  8500.00,
  10000.00,
  'PDE001',
  25,
  (SELECT id FROM categories WHERE slug = 'earrings'),
  ARRAY['/images/products/pearl-earrings-1.jpg', '/images/products/pearl-earrings-2.jpg'],
  ARRAY['pearl', 'drop', 'sterling-silver', 'classic'],
  true,
  true,
  'Sterling Silver',
  'White',
  'Pearl',
  '925',
  12
),
(
  'Ruby Engagement Ring',
  'ruby-engagement-ring',
  'Exquisite ruby engagement ring featuring a oval-cut ruby surrounded by diamonds in a halo setting. Set in 18k yellow gold.',
  'Stunning ruby engagement ring with diamond halo',
  85000.00,
  95000.00,
  'RER001',
  8,
  (SELECT id FROM categories WHERE slug = 'rings'),
  ARRAY['/images/products/ruby-ring-1.jpg', '/images/products/ruby-ring-2.jpg'],
  ARRAY['ruby', 'engagement', 'diamond', 'halo', 'yellow-gold'],
  true,
  true,
  '18k Yellow Gold',
  'Red',
  'Ruby, Diamond',
  '18k',
  36
),
(
  'Tennis Bracelet',
  'tennis-bracelet',
  'Classic tennis bracelet featuring a continuous line of brilliant-cut diamonds set in 14k white gold. A timeless piece for any jewelry collection.',
  'Classic diamond tennis bracelet in 14k white gold',
  125000.00,
  140000.00,
  'TB001',
  5,
  (SELECT id FROM categories WHERE slug = 'bracelets'),
  ARRAY['/images/products/tennis-bracelet-1.jpg', '/images/products/tennis-bracelet-2.jpg'],
  ARRAY['tennis', 'diamond', 'white-gold', 'classic'],
  true,
  true,
  '14k White Gold',
  'White',
  'Diamond',
  '14k',
  24
),
(
  'Sapphire Pendant',
  'sapphire-pendant',
  'Beautiful sapphire pendant featuring a pear-shaped blue sapphire surrounded by diamonds. Comes with an 18-inch white gold chain.',
  'Elegant sapphire pendant with diamond accents',
  35000.00,
  40000.00,
  'SP001',
  12,
  (SELECT id FROM categories WHERE slug = 'pendants'),
  ARRAY['/images/products/sapphire-pendant-1.jpg', '/images/products/sapphire-pendant-2.jpg'],
  ARRAY['sapphire', 'pendant', 'diamond', 'blue', 'white-gold'],
  false,
  true,
  '18k White Gold',
  'Blue',
  'Sapphire, Diamond',
  '18k',
  24
),
(
  'Gold Bangle Set',
  'gold-bangle-set',
  'Traditional gold bangle set crafted in 22k yellow gold. Features intricate Indian patterns and designs. Set of 2 bangles.',
  'Traditional 22k gold bangle set with Indian patterns',
  55000.00,
  60000.00,
  'GBS001',
  20,
  (SELECT id FROM categories WHERE slug = 'bangles'),
  ARRAY['/images/products/gold-bangles-1.jpg', '/images/products/gold-bangles-2.jpg'],
  ARRAY['gold', 'bangles', 'traditional', 'indian', 'set'],
  false,
  true,
  '22k Yellow Gold',
  'Gold',
  NULL,
  '22k',
  12
),
(
  'Emerald Stud Earrings',
  'emerald-stud-earrings',
  'Elegant emerald stud earrings featuring round-cut emeralds set in 14k yellow gold. Perfect for everyday wear or special occasions.',
  'Beautiful emerald stud earrings in 14k yellow gold',
  18000.00,
  22000.00,
  'ESE001',
  18,
  (SELECT id FROM categories WHERE slug = 'earrings'),
  ARRAY['/images/products/emerald-studs-1.jpg', '/images/products/emerald-studs-2.jpg'],
  ARRAY['emerald', 'stud', 'yellow-gold', 'round'],
  false,
  true,
  '14k Yellow Gold',
  'Green',
  'Emerald',
  '14k',
  18
),
(
  'Vintage Charm Bracelet',
  'vintage-charm-bracelet',
  'Vintage-inspired charm bracelet in sterling silver with various decorative charms. Each charm tells a story and adds personality to your style.',
  'Vintage-style charm bracelet with decorative charms',
  12000.00,
  15000.00,
  'VCB001',
  30,
  (SELECT id FROM categories WHERE slug = 'bracelets'),
  ARRAY['/images/products/charm-bracelet-1.jpg', '/images/products/charm-bracelet-2.jpg'],
  ARRAY['vintage', 'charm', 'sterling-silver', 'decorative'],
  false,
  true,
  'Sterling Silver',
  'Silver',
  NULL,
  '925',
  12
);
